[server.http]
port = 9111
[server.grpc]
port = 9112
enableAccessInterceptorReq = true
enableAccessInterceptorRes = true
[server.governor]
port = 9113
[etcd]
addrs=["172.22.0.1:2379"]
[registry]
    connectTimeout = "1s"
    secure = false
[mysql.video]
    connMaxLifetime = "300s"
    debug = true
    dsn = "user:password@tcp(172.22.0.1:3306)/gocn_resource?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local"
    level = "panic"
    maxIdleConns = 50
    maxOpenConns = 100
