[server.http]
port = 9111
[server.grpc]
port = 9112
enableAccessInterceptorReq = true
enableAccessInterceptorRes = true
[server.governor]
port = 9113
[etcd]
addrs=["etcd:2379"]
[registry]
    connectTimeout = "1s"
    secure = false
[mysql.video]
    connMaxLifetime = "300s"
    debug = true
    dsn = "fastgocn:helloguys@tcp(mysql:3306)/fastgocn?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=1s&readTimeout=3s&writeTimeout=3s"
    level = "panic"
    maxIdleConns = 50
    maxOpenConns = 100
