[server.http]
host = "0.0.0.0"
port = 8010
[server.governor]
host = "0.0.0.0"
port = 8011
[logger.default]
    level = "debug"
[etcd]
addrs=["etcd:2379"]
[registry]
connectTimeout = "10s"
secure = false
[grpc.usersrv]
addr = "user-srv:9091"
balancerName = "round_robin" # 默认值
block =  false # 默认值
dialTimeout = "10s" # 默认值
[grpc.resourcesrv]
addr = "resource-srv:9112"
balancerName = "round_robin" # 默认值
block =  false # 默认值
readTimeout = "100s"
dialTimeout = "10s" # 默认值