[server.http]
host = "0.0.0.0"
port = 8010
[server.governor]
host = "0.0.0.0"
port = 8011
[logger.default]
level="debug"
[etcd]
addrs = ["127.0.0.1:2379"]
connectTimeout = "10s"
[registry]
connectTimeout = "3s"
secure = false
[grpc.usersrv]
addr = "etcd:///user-srv"
balancerName = "round_robin" # 默认值
dialTimeout = "1s" # 默认值
enableAccessInterceptor = true
enableAccessInterceptorReply = true
enableAccessInterceptorReq = true
[grpc.resourcesrv]
addr = "etcd:///resource-srv"
balancerName = "round_robin" # 默认值
readTimeout = "100s"
dialTimeout = "1s" # 默认值
enableAccessInterceptor = true
enableAccessInterceptorReply = true
enableAccessInterceptorReq = true
